name: slack-notification-action
description: GitHub Action for Slack notifications
inputs:
  SLACK_WEBHOOK_URL:
    required: true
  NOTIFICATION_TYPE:
    required: true
  TITLE:
    required: false
  BODY:
    required: true
  URL_WORKFLOW:
    required: false
    default: "https://github.com/${{ github.repository }}/commit/${{ github.sha }}/checks"
runs:
  using: 'node24'
  main: 'dist/index.js'
